"""empty message

Revision ID: 889382b50633
Revises: 15791a4b1d49
Create Date: 2021-12-07 23:36:53.900502

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '889382b50633'
down_revision = '15791a4b1d49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collab_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('og_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['og_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collaboration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mush_img', sa.String(length=150), nullable=True),
    sa.Column('spore_img', sa.String(length=150), nullable=True),
    sa.Column('description', sa.String(length=350), nullable=True),
    sa.Column('collab_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collab_user_id'], ['collab_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('observation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('body', sa.String(length=150), nullable=True),
    sa.Column('img_url', sa.String(length=150), nullable=True),
    sa.Column('collab_user_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collab_user_id'], ['collab_user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('body', sa.String(length=150), nullable=True),
    sa.Column('pub_date', sa.Date(), nullable=True),
    sa.Column('collab_user_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collab_user_id'], ['collab_user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attribute_description',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('species', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=50), nullable=True),
    sa.Column('substrate', sa.String(length=50), nullable=True),
    sa.Column('gills', sa.String(length=50), nullable=True),
    sa.Column('pores', sa.String(length=50), nullable=True),
    sa.Column('pileus_diameter', sa.Integer(), nullable=True),
    sa.Column('shape', sa.String(length=50), nullable=True),
    sa.Column('pileus_color', sa.String(length=50), nullable=True),
    sa.Column('margin', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('foot_color', sa.String(length=50), nullable=True),
    sa.Column('ring', sa.Boolean(), nullable=True),
    sa.Column('foot_diameter', sa.Integer(), nullable=True),
    sa.Column('volva', sa.Boolean(), nullable=True),
    sa.Column('collaboration_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collaboration_id'], ['collaboration.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mushrooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('local_name', sa.String(length=150), nullable=True),
    sa.Column('scientific_name', sa.String(length=150), nullable=True),
    sa.Column('edible', sa.String(length=150), nullable=True),
    sa.Column('hallucinogen', sa.Boolean(), nullable=True),
    sa.Column('location', sa.String(length=80), nullable=True),
    sa.Column('data_description', sa.String(length=300), nullable=True),
    sa.Column('recipe', sa.String(length=300), nullable=True),
    sa.Column('viewers', sa.Integer(), nullable=True),
    sa.Column('observation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['observation_id'], ['observation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commentary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('pub_date', sa.Date(), nullable=True),
    sa.Column('viewers', sa.Integer(), nullable=True),
    sa.Column('body', sa.String(length=150), nullable=True),
    sa.Column('collab_user_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('mushroom_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collab_user_id'], ['collab_user.id'], ),
    sa.ForeignKeyConstraint(['mushroom_id'], ['mushrooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('first_name', sa.String(length=80), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(length=80), nullable=True))
    op.add_column('user', sa.Column('favorites', sa.Integer(), nullable=True))
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.drop_column('user', 'favorites')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    op.drop_table('commentary')
    op.drop_table('mushrooms')
    op.drop_table('attribute_description')
    op.drop_table('post')
    op.drop_table('observation')
    op.drop_table('collaboration')
    op.drop_table('collab_user')
    # ### end Alembic commands ###
